import Foundation
public struct EvaartaWorkTask:Sendable{public var id:String;public var title:String;public var status:String;public var priority:String;public var assigneeId:String?;public var teamId:String?;public var projectId:String?;public var parentId:String?;public var dependsOn:[String];public var estimateMinutes:Int;public var remainingMinutes:Int;public var progress:Int;public var skills:[String];public var evidenceIds:[String];public var decisionIds:[String];public var sourceIds:[String];public var due:Date?;public var updated:Date;public var assignmentState:String;public init(id:String,title:String,status:String="inbox",priority:String="medium",assigneeId:String?=nil,teamId:String?=nil,projectId:String?=nil,parentId:String?=nil,dependsOn:[String]=[],estimateMinutes:Int=0,remainingMinutes:Int?=nil,progress:Int=0,skills:[String]=[],evidenceIds:[String]=[],decisionIds:[String]=[],sourceIds:[String]=[],due:Date?=nil,updated:Date=Date(),assignmentState:String="none"){self.id=id;self.title=title;self.status=status;self.priority=priority;self.assigneeId=assigneeId;self.teamId=teamId;self.projectId=projectId;self.parentId=parentId;self.dependsOn=dependsOn;self.estimateMinutes=estimateMinutes;self.remainingMinutes=remainingMinutes ?? estimateMinutes;self.progress=progress;self.skills=skills;self.evidenceIds=evidenceIds;self.decisionIds=decisionIds;self.sourceIds=sourceIds;self.due=due;self.updated=updated;self.assignmentState=assignmentState}}
public struct EvaartaCandidate:Sendable{public let id:String;public let skills:Set<String>;public let capacityMinutes:Int;public let committedMinutes:Int;public let authorized:Bool;public let projectIds:Set<String>;public init(id:String,skills:Set<String>=[],capacityMinutes:Int=0,committedMinutes:Int=0,authorized:Bool=true,projectIds:Set<String>=[]){self.id=id;self.skills=skills;self.capacityMinutes=capacityMinutes;self.committedMinutes=committedMinutes;self.authorized=authorized;self.projectIds=projectIds}}
public struct EvaartaWorkHealth:Sendable{public let health:String;public let score:Int;public let overdue:Bool;public let stalled:Bool;public let missingEvidence:Bool;public let causes:Set<String>}
public enum EvaartaTaskWorkOperatingSystem{
 public static let states=["inbox","planned","ready","offered","assigned","accepted","in-progress","waiting","blocked","review","approved","verified","done","cancelled","deferred","rejected","duplicate"]
 public static func assign(_ t:EvaartaWorkTask,_ c:EvaartaCandidate)->EvaartaWorkTask{var x=t;x.assigneeId=c.id;x.assignmentState="offered";x.status="offered";return x}
 public static func negotiate(_ t:EvaartaWorkTask,_ state:String)->EvaartaWorkTask{var x=t;x.assignmentState=state;x.status=state=="accepted" ? "accepted":state=="declined" ? "rejected":"offered";return x}
 public static func validateGraph(_ ts:[EvaartaWorkTask])->Bool{var seen=Set<String>();var visiting=Set<String>();func d(_ id:String)->Bool{if visiting.contains(id){return false};if seen.contains(id){return true};guard let t=ts.first(where:{$0.id==id})else{return false};visiting.insert(id);for x in t.dependsOn{if !d(x){return false}};visiting.remove(id);seen.insert(id);return true};return ts.allSatisfy{d($0.id)}}
 public static func recommend(_ t:EvaartaWorkTask,_ cs:[EvaartaCandidate])->[(String,Double)]{cs.filter{$0.authorized}.map{c in let skill=t.skills.isEmpty ? 1:Double(t.skills.filter{c.skills.contains($0)}.count)/Double(t.skills.count);let availability=c.capacityMinutes>0 ? max(0,Double(c.capacityMinutes-c.committedMinutes)/Double(c.capacityMinutes)):1;let membership=t.projectId==nil || c.projectIds.contains(t.projectId!) ? 1:0;return(c.id,.45*skill+.35*availability+.20*membership)}.sorted{$0.1>$1.1}}
 public static func monitor(_ t:EvaartaWorkTask,now:Date=Date(),staleHours:Double=72)->EvaartaWorkHealth{let overdue=t.due != nil && now>t.due! && !["done","verified","cancelled"].contains(t.status);let stalled=now.timeIntervalSince(t.updated)>=staleHours*3600;let unassigned=t.assigneeId==nil&&t.teamId==nil;let h=t.status=="blocked" ? "blocked":unassigned ? "unassigned":t.assignmentState=="offered" ? "unaccepted":overdue ? "late":stalled ? "stalled":"on-track";var s=100;if overdue{s-=30};if stalled{s-=20};if h=="blocked"{s-=25};if unassigned{s-=15};return EvaartaWorkHealth(health:h,score:max(0,s),overdue:overdue,stalled:stalled,missingEvidence:t.status=="review"&&t.evidenceIds.isEmpty,causes:h=="blocked" ? ["dependency"]:[])}
 public static func impact(_ ts:[EvaartaWorkTask],_ id:String)->Set<String>{var out=Set<String>();var q=[id];while !q.isEmpty{let next=ts.filter{$0.dependsOn.contains(where:q.contains)&&!out.contains($0.id)}.map{$0.id};out.formUnion(next);q=next};return out}
 public static func verify(_ t:EvaartaWorkTask,allowWithoutEvidence:Bool=false)->EvaartaWorkTask{precondition(allowWithoutEvidence || !t.evidenceIds.isEmpty,"verification requires evidence");var x=t;x.status="verified";return x}
 public static func projectHealth(_ ts:[EvaartaWorkTask])->String{let hs=ts.map{monitor($0).health};return hs.contains(where:{["blocked","late"].contains($0)}) ? "at-risk":hs.contains(where:{["stalled","unassigned","unaccepted"].contains($0)}) ? "watch":"on-track"}
}
