import Foundation

public struct EvaartaPerson:Sendable { public let id:String; public let name:String; public let addresses:[String]; public let phones:[String]; public init(id:String,name:String="",addresses:[String]=[],phones:[String]=[]){self.id=id;self.name=name;self.addresses=addresses;self.phones=phones} }
public struct EvaartaConversation:Sendable { public let id:String; public let title:String; public let participantIds:[String]; public let channel:String; public let projectId:String?; public init(id:String,title:String="",participantIds:[String]=[],channel:String="chat",projectId:String?=nil){self.id=id;self.title=title;self.participantIds=participantIds;self.channel=channel;self.projectId=projectId} }
public struct EvaartaMessage:Sendable { public let id:String; public let conversationId:String; public let senderId:String; public let body:String; public let channel:String; public let recipientIds:[String]; public let threadId:String?; public let state:String; public let evidenceIds:[String]; public let timestamp:Date; public init(id:String,conversationId:String,senderId:String,body:String="",channel:String="chat",recipientIds:[String]=[],threadId:String?=nil,state:String="sent",evidenceIds:[String]=[],timestamp:Date=Date()){self.id=id;self.conversationId=conversationId;self.senderId=senderId;self.body=body;self.channel=channel;self.recipientIds=recipientIds;self.threadId=threadId;self.state=state;self.evidenceIds=evidenceIds;self.timestamp=timestamp} }
public struct EvaartaCommunicationEvent:Sendable { public let id:String; public let idempotencyKey:String; public let entityId:String; public let baseVersion:Int?; public let currentVersion:Int? }
public enum EvaartaCommunicationSuite {
 public static func identityMatch(_ people:[EvaartaPerson],addresses:[String],phones:[String])->[EvaartaPerson]{people.filter{p in p.addresses.contains(where:addresses.contains)||p.phones.contains(where:phones.contains)}}
 public static func search(_ messages:[EvaartaMessage],query:String)->[EvaartaMessage]{messages.filter{$0.body.localizedCaseInsensitiveContains(query)}}
 public static func reconcile(_ events:[EvaartaCommunicationEvent])->(accepted:[EvaartaCommunicationEvent],conflicts:[EvaartaCommunicationEvent]){var seen=Set<String>(),a=[EvaartaCommunicationEvent](),c=[EvaartaCommunicationEvent]();for e in events{if !seen.insert(e.idempotencyKey).inserted{continue};if let b=e.baseVersion,let v=e.currentVersion,b != v{c.append(e)}else{a.append(e)}};return(a,c)}
 public static func contract()->[String]{["universal-message-model","conversation-store","people-identity-resolution","provider-adapters","unified-inbox","offline-send-queue","calendar-engine","meeting-workspace","external-channel-adapters","communication-ai","workflow-automation","encryption-boundary","policy-dlp","retention","legal-hold","audit","interoperability"]}
}
