import Foundation
public struct EvaartaPhaseFTask:Sendable{public var id:String;public var title:String;public var status:String="inbox";public var assigneeId:String?;public var projectId:String?;public var dependsOn:[String]=[];public var estimateMinutes:Int=0;public var remainingMinutes:Int=0;public var skills:Set<String>=[];public var evidenceIds:[String]=[];public var due:Date?;public var updated:Date=Date();public init(id:String,title:String,status:String="inbox",assigneeId:String?=nil,projectId:String?=nil,dependsOn:[String]=[],estimateMinutes:Int=0,remainingMinutes:Int?=nil,skills:Set<String>=[],evidenceIds:[String]=[],due:Date?=nil,updated:Date=Date()){self.id=id;self.title=title;self.status=status;self.assigneeId=assigneeId;self.projectId=projectId;self.dependsOn=dependsOn;self.estimateMinutes=estimateMinutes;self.remainingMinutes=remainingMinutes ?? estimateMinutes;self.skills=skills;self.evidenceIds=evidenceIds;self.due=due;self.updated=updated}}
public struct EvaartaPhaseFAssignmentScore:Sendable{public let personId:String;public let score:Double;public let skill:Double;public let availability:Double;public let membership:Double}
public enum EvaartaTaskWorkPhaseF{
 public static func validateGraph(_ ts:[EvaartaPhaseFTask])->Bool{var seen=Set<String>();var visiting=Set<String>();func d(_ id:String)->Bool{if visiting.contains(id){return false};if seen.contains(id){return true};guard let t=ts.first(where:{$0.id==id})else{return false};visiting.insert(id);for x in t.dependsOn{if !d(x){return false}};visiting.remove(id);seen.insert(id);return true};return ts.allSatisfy{d($0.id)}}
 public static func score(_ t:EvaartaPhaseFTask,personId:String,skills:Set<String>,capacity:Int,committed:Int,membership:Bool=true)->EvaartaPhaseFAssignmentScore{let skill=t.skills.isEmpty ? 1:Double(t.skills.filter{skills.contains($0)}.count)/Double(t.skills.count);let avail=capacity>0 ? max(0,Double(capacity-committed)/Double(capacity)):1;let m=membership ? 1:0;return .init(personId:personId,score:.45*skill+.35*avail+.20*m,skill:skill,availability:avail,membership:m)}
 public static func monitor(_ t:EvaartaPhaseFTask,now:Date=Date())->String{if t.status=="blocked"{return "blocked"};if t.assigneeId==nil{return "unassigned"};if let d=t.due,now>d&&!["done","verified","cancelled"].contains(t.status){return "late"};if now.timeIntervalSince(t.updated)>=72*3600{return "stalled"};return "on-track"}
 public static func impact(_ ts:[EvaartaPhaseFTask],_ id:String)->Set<String>{var out=Set<String>();var q=[id];while !q.isEmpty{let next=ts.filter{$0.dependsOn.contains(where:q.contains)&&!out.contains($0.id)}.map{$0.id};out.formUnion(next);q=next};return out}
 public static func verify(_ t:EvaartaPhaseFTask,allowWithoutEvidence:Bool=false)->EvaartaPhaseFTask{precondition(allowWithoutEvidence || !t.evidenceIds.isEmpty);var x=t;x.status="verified";return x}
 public static func evidenceCompletion(_ t:EvaartaPhaseFTask,_ evidence:[String])->EvaartaPhaseFTask{var x=t;x.evidenceIds=Array(Set(t.evidenceIds+evidence));x.status="review";return x}
}
