import Foundation
public struct EvaartaAnchor: Codable, Equatable { public let documentId:String; public let revisionId:String?; public let page:Int?; public let startOffset:Int?; public let endOffset:Int?; public let quote:String?; public let selector:String?; public let rects:[Double]?; public init(documentId:String,revisionId:String?=nil,page:Int?=nil,startOffset:Int?=nil,endOffset:Int?=nil,quote:String?=nil,selector:String?=nil,rects:[Double]?=nil){self.documentId=documentId;self.revisionId=revisionId;self.page=page;self.startOffset=startOffset;self.endOffset=endOffset;self.quote=quote;self.selector=selector;self.rects=rects}}
public enum EvaartaEntityKind:String,Codable {case document,revision,annotation,evidence,note,claim,argument,finding,decision,task,person,project,source}
public enum EvaartaRelation:String,Codable {case supports,contradicts,derivedFrom="derived-from",references,relatesTo="relates-to",qualifies,answers,raises,dependsOn="depends-on",implements,resultsIn="results-in",assignedTo="assigned-to",verifiedBy="verified-by",supersedes}
public struct EvaartaEntity:Codable,Identifiable {public let id:String;public let kind:EvaartaEntityKind;public var data:[String:String];public init(id:String=UUID().uuidString,kind:EvaartaEntityKind,data:[String:String]=[:]){self.id=id;self.kind=kind;self.data=data}}
public struct EvaartaRelationEdge:Codable,Identifiable {public let id:String;public let fromId:String;public let toId:String;public let kind:EvaartaRelation;public let confidence:Double?;public init(id:String=UUID().uuidString,fromId:String,toId:String,kind:EvaartaRelation,confidence:Double?=nil){self.id=id;self.fromId=fromId;self.toId=toId;self.kind=kind;self.confidence=confidence}}
public struct EvaartaEvidence:Codable,Identifiable {public let id:String;public let documentId:String;public let revisionId:String?;public let anchor:EvaartaAnchor;public let text:String;public let type:String;public let status:String;public init(id:String=UUID().uuidString,documentId:String,revisionId:String?,anchor:EvaartaAnchor,text:String,type:String="quote",status:String="active"){self.id=id;self.documentId=documentId;self.revisionId=revisionId;self.anchor=anchor;self.text=text.trimmingCharacters(in:.whitespacesAndNewlines);self.type=type;self.status=status}}
public struct EvaartaCanvasNode:Codable,Identifiable {public let id:String;public let entityId:String;public let kind:EvaartaEntityKind;public var x:Double;public var y:Double;public var width:Double;public var height:Double;public init(id:String=UUID().uuidString,entityId:String,kind:EvaartaEntityKind,x:Double=0,y:Double=0,width:Double=280,height:Double=160){self.id=id;self.entityId=entityId;self.kind=kind;self.x=x;self.y=y;self.width=width;self.height=height}}
public struct EvaartaCanvas:Codable,Identifiable {public let id:String;public var title:String;public var nodes:[EvaartaCanvasNode];public var edges:[EvaartaRelationEdge];public init(id:String=UUID().uuidString,title:String="Evidence Workspace",nodes:[EvaartaCanvasNode]=[],edges:[EvaartaRelationEdge]=[]){self.id=id;self.title=title;self.nodes=nodes;self.edges=edges}}
public enum EvaartaKnowledgeSuite {
 public static func evidence(documentId:String,anchor:EvaartaAnchor,text:String,type:String="quote")->EvaartaEvidence{EvaartaEvidence(documentId:documentId,revisionId:anchor.revisionId,anchor:anchor,text:text,type:type)}
 public static func relation(from:String,to:String,kind:EvaartaRelation)->EvaartaRelationEdge{EvaartaRelationEdge(fromId:from,toId:to,kind:kind)}
 public static func lineage(_ id:String,relations:[EvaartaRelationEdge],upstream:Bool=true)->[String]{var result:[String]=[];var frontier=[id];var seen:Set<String>=[id];for _ in 0..<20 where !frontier.isEmpty{var next:[String]=[];for current in frontier{for r in relations{let c=upstream ? (r.toId==current ? r.fromId:nil) : (r.fromId==current ? r.toId:nil);if let c,seen.insert(c).inserted{next.append(c);result.append(c)}}};frontier=next};return result}
 public static func projectStatus(_ entities:[EvaartaEntity])->(total:Int,completed:Int,open:Int){let tasks=entities.filter{$0.kind == .task};let completed=tasks.filter{$0.data["status"]=="completed"}.count;return(tasks.count,completed,tasks.count-completed)}
}
